# Generated by Django 4.2.30 on 2026-09-10 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your log a unique title.', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL friendly shortcut string.', max_length=200, unique=True)),
                ('species_name', models.CharField(max_length=150, verbose_name='Bird Species')),
                ('location_spotted', models.CharField(max_length=255, verbose_name='Location Details')),
                ('date_spotted', models.DateField(help_text='When did you see this bird?')),
                ('notes', models.TextField(help_text='Describe behavior, plumage, environment, etc.')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bird_sightings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_spotted', '-created_on'],
            },
        ),
    ]
