# Generated by Django 4.2.30 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='summary',
            field=models.TextField(blank=True, help_text='A short summary or teaser of the sighting (optional).', null=True),
        ),
    ]
