# Generated by Django 4.2.30 on 2026-09-11 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightings', '0002_sighting_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the sighting (optional).', null=True, upload_to='sightings/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Write your comment or sighting verification here.')),
                ('approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('sighting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sightings.sighting')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
