# Generated by Django 4.2.30 on 2026-09-11 14:48

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_sighting_image_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='notes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Field Notes'),
        ),
    ]
